version: "2"

services:

  snoop-pg:
    image: postgres:9.6
    volumes:
      - ./volumes/snoop-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: snoop
      POSTGRES_DATABASE: snoop

  snoop-rabbitmq:
    image: rabbitmq:3.7

  snoop-tika:
    image: logicalspark/docker-tikaserver

  snoop-worker:
    #TODO image: liquidinvestigations/hoover-snoop2
    image: snoop2
    volumes:
      - ./collections:/opt/hoover/collections
      - ./snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
    depends_on:
      - snoop-pg
      - snoop-rabbitmq
      - snoop-tika
    env_file:
      - snoop.env
    command: ./manage.py runworker

  snoop:
    #TODO image: liquidinvestigations/hoover-snoop2
    image: snoop2
    volumes:
      - ./collections:/opt/hoover/collections
      - ./snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
    depends_on:
      - snoop-pg
      - snoop-rabbitmq
      - snoop-tika
    env_file:
      - snoop.env

  search-pg:
    image: postgres:9.6
    volumes:
      - ./volumes/search-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: search
      POSTGRES_DATABASE: search

  search-es:
    image: elasticsearch:2
    volumes:
      - ./volumes/search-es/data:/usr/share/elasticsearch/data

  ui:
    image: liquidinvestigations/hoover-ui
    volumes:
      - ./ui/build:/opt/hoover/ui/build

  search:
    image: liquidinvestigations/hoover-search
    volumes:
      - ./ui/build:/opt/hoover/ui/build
      - ./volumes/metrics:/opt/hoover/metrics
      - ./search-settings.py:/opt/hoover/search/hoover/site/settings/local.py
    depends_on:
      - search-pg
      - search-es
      - ui
      - snoop
    env_file:
      - search.env

  nginx:
    image: nginx
    command: /bin/bash -c "envsubst '$$NGINX_SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
    ports:
      - 80:80
    depends_on:
      - search
    env_file:
      - nginx.env
