version: "3.3"

volumes:
  snoop-stats-es-data: {}

services:
  snoop-rabbitmq:
    image: rabbitmq:3.7.3

  snoop-tika:
    image: logicalspark/docker-tikaserver

  search-pg:
    image: postgres:9.6
    volumes:
      - ./volumes/search-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: search
      POSTGRES_DATABASE: search

  search-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    volumes:
      - ./volumes/search-es/data:/usr/share/elasticsearch/data
      - ./volumes/search-es-snapshots:/opt/hoover/es-snapshots
    environment:
      discovery.type: single-node
      path.repo: /opt/hoover/es-snapshots

  ui:
    image: liquidinvestigations/hoover-ui
    volumes:
      - ./ui/build:/opt/hoover/ui/build

  search:
    image: liquidinvestigations/hoover-search
    volumes:
      - ./ui/build:/opt/hoover/ui/build
      - ./volumes/metrics:/opt/hoover/metrics
      - ./settings/search-settings.py:/opt/hoover/search/hoover/site/settings/local.py
      - ./settings/search-settings-testing.py:/opt/hoover/search/hoover/site/settings/testing_local.py
    depends_on:
      - search-pg
      - search-es
      - ui
    env_file:
      - ./settings/search.env
    ports:
      - "45024:80"
    environment:
      WAIT_HOSTS: search-es:9200, search-pg:5432
      WAIT_HOSTS_TIMEOUT: 60
      
  nextcloud-pg:
    image: postgres:9.6
    restart: always
    volumes:
      - ./volumes/nextcloud-pg/data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      
  nextcloud:
    image: nextcloud
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html
      - ./collections/ncsync:/var/www/html/data/ncsync/files
    depends_on:
      - nextcloud-pg
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: nextcloud-pg
      OC_PASS: secret
    ports:
      - "15025:80"
      
  snoop-pg--ncsync:
    image: postgres:9.6
    environment:
      POSTGRES_USER: snoop
      POSTGRES_DATABASE: snoop
    volumes:
      - ./volumes/snoop-pg--ncsync/data:/var/lib/postgresql/data

  snoop-worker--ncsync:
    image: snoop2
    volumes:
      - ./gnupg:/opt/hoover/gnupg
      - ./collections/ncsync:/opt/hoover/snoop/collection
      - ./settings/ncsync/snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
      - ./snoop-blobs/ncsync:/opt/hoover/snoop/blobs
    env_file:
      - ./settings/ncsync/snoop.env
    depends_on:
      - snoop-rabbitmq
      - snoop-tika
      - search-es
      - snoop-pg--ncsync
    ports:
      - "15556:5555"
    command: ./manage.py runworkers -s

  snoop--ncsync:
    image: liquidinvestigations/hoover-snoop2
    volumes:
      - ./gnupg:/opt/hoover/gnupg
      - ./collections/ncsync:/opt/hoover/snoop/collection
      - ./volumes/search-es-snapshots:/opt/hoover/es-snapshots
      - ./settings/ncsync/snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
      - ./snoop-blobs/ncsync:/opt/hoover/snoop/blobs
    ports:
      - "45026:80"
    env_file:
      - ./settings/ncsync/snoop.env
    environment:
      WAIT_HOSTS: search-es:9200, snoop-pg--ncsync:5432
      WAIT_HOSTS_TIMEOUT: 60
    depends_on:
      - snoop-rabbitmq
      - snoop-tika
      - search-es
      - snoop-pg--ncsync  
    
    
      