version: "2"

services:

  snoop-pg:
    image: postgres:9.6
    volumes:
      - ./docker-volumes/snoop-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: snoop
      POSTGRES_DATABASE: snoop

  snoop-tika:
    image: logicalspark/docker-tikaserver

  snoop:
    build: ./snoop
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - ./snoop:/opt/hoover/snoop
      - ./cache:/opt/hoover/cache
      - ./datasets:/opt/hoover/datasets
      - ./testdata:/opt/hoover/testdata
      - ./docker-snoop-settings.py:/opt/hoover/snoop/snoop/site/settings/local.py
    ports:
      - 8001:8001
    depends_on:
      - snoop-pg
      - snoop-tika
      - search-es
    env_file:
      - docker-snoop.env

  search-pg:
    image: postgres:9.6
    volumes:
      - ./docker-volumes/search-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: search
      POSTGRES_DATABASE: search

  search-es:
    image: elasticsearch:2
    volumes:
      - ./docker-volumes/search-es/data:/usr/share/elasticsearch/data

  search:
    build: ./search
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./search:/opt/hoover/search
      - ./ui/build:/opt/hoover/ui/build
      - ./metrics:/opt/hoover/metrics
      - ./docker-search-settings.py:/opt/hoover/search/hoover/site/settings/local.py
    ports:
      - 8000:8000
    depends_on:
      - search-pg
      - search-es
      - snoop
    env_file:
      - docker-search.env
