version: "2"

services:

  snoop-pg:
    image: postgres:9.6
    volumes:
      - ./volumes/snoop-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: snoop
      POSTGRES_DATABASE: snoop

  snoop-rabbitmq:
    image: rabbitmq:3.7

  snoop-tika:
    image: logicalspark/docker-tikaserver

  snoop-worker:
    image: liquidinvestigations/hoover-snoop2
    volumes:
      - ./collections:/opt/hoover/collections
      - ./snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
      - ./snoop-blobs:/opt/hoover/snoop/blobs
    depends_on:
      - snoop-pg
      - snoop-rabbitmq
      - snoop-tika
    env_file:
      - snoop.env
    command: ./manage.py runworkers

  snoop:
    image: liquidinvestigations/hoover-snoop2
    volumes:
      - ./collections:/opt/hoover/collections
      - ./snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
      - ./snoop-blobs:/opt/hoover/snoop/blobs
    depends_on:
      - snoop-pg
      - snoop-rabbitmq
      - snoop-tika
    env_file:
      - snoop.env
    ports:
      - 45023:80

  search-pg:
    image: postgres:9.6
    volumes:
      - ./volumes/search-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: search
      POSTGRES_DATABASE: search

  search-es:
    image: elasticsearch:2
    volumes:
      - ./volumes/search-es/data:/usr/share/elasticsearch/data

  ui:
    image: liquidinvestigations/hoover-ui
    volumes:
      - ./ui/build:/opt/hoover/ui/build

  search:
    image: liquidinvestigations/hoover-search
    volumes:
      - ./ui/build:/opt/hoover/ui/build
      - ./volumes/metrics:/opt/hoover/metrics
      - ./search-settings.py:/opt/hoover/search/hoover/site/settings/local.py
    depends_on:
      - search-pg
      - search-es
      - ui
      - snoop
    env_file:
      - search.env
    ports:
      - 45024:80
