version: "2"

services:

  snoop-pg:
    image: postgres:9.6
    volumes:
      - /opt/hoover/docker-volumes/snoop-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: snoop
      POSTGRES_DATABASE: snoop

  snoop-tika:
    image: logicalspark/docker-tikaserver

  snoop:
    build: ./snoop
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - /opt/hoover/snoop:/opt/hoover/snoop
      - /opt/hoover/cache:/opt/hoover/cache
      - /opt/hoover/datasets:/opt/hoover/datasets
      - /opt/hoover/testdata:/opt/hoover/testdata
    ports:
      - 8001:8001
    depends_on:
      - snoop-pg
      - snoop-tika
      - search-es

  search-pg:
    image: postgres:9.6
    volumes:
      - /opt/hoover/docker-volumes/search-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: search
      POSTGRES_DATABASE: search

  search-es:
    image: elasticsearch:2
    volumes:
      - /opt/hoover/docker-volumes/search-es/data:/usr/share/elasticsearch/data

  search:
    build: ./search
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - /opt/hoover/search:/opt/hoover/search
      - /opt/hoover/ui/build:/opt/hoover/ui/build
      - /opt/hoover/metrics:/opt/hoover/metrics
    ports:
      - 8000:8000
    depends_on:
      - search-pg
      - search-es
      - snoop
