version: "2"

services:

  snoop-pg:
    image: postgres:9.6
    volumes:
      - ./volumes/snoop-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: snoop
      POSTGRES_DATABASE: snoop

  snoop-rabbitmq:
    image: rabbitmq:3.7.3

  snoop-tika:
    image: logicalspark/docker-tikaserver

  snoop-stats-es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits: {memlock: {soft: -1, hard: -1}}
    volumes:
      - snoop-stats-es-data:/usr/share/elasticsearch/data

  snoop-stats-kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    depends_on:
      - snoop-stats-es
    environment:
      ELASTICSEARCH_URL: 'http://snoop-stats-es:9200'
    ports:
      - 45022:5601

  snoop-worker:
    image: liquidinvestigations/hoover-snoop2
    volumes:
      - ./gnupg:/opt/hoover/gnupg
      - ./collections:/opt/hoover/collections
      - ./snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
      - ./snoop-blobs:/opt/hoover/snoop/blobs
    depends_on:
      - snoop-pg
      - snoop-rabbitmq
      - snoop-tika
      - snoop-stats-es
      - search-es
    env_file:
      - snoop.env
    command: ./manage.py runworkers

  snoop:
    image: liquidinvestigations/hoover-snoop2
    volumes:
      - ./gnupg:/opt/hoover/gnupg
      - ./collections:/opt/hoover/collections
      - ./snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
      - ./snoop-blobs:/opt/hoover/snoop/blobs
      - ./volumes/search-es-snapshots:/opt/hoover/es-snapshots
    depends_on:
      - snoop-pg
      - snoop-rabbitmq
      - snoop-tika
      - snoop-stats-es
      - search-es
    env_file:
      - snoop.env
    ports:
      - 45023:80

  search-pg:
    image: postgres:9.6
    volumes:
      - ./volumes/search-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: search
      POSTGRES_DATABASE: search

  search-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    volumes:
      - ./volumes/search-es/data:/usr/share/elasticsearch/data
      - ./volumes/search-es-snapshots:/opt/hoover/es-snapshots
    environment:
      discovery.type: single-node
      path.repo: /opt/hoover/es-snapshots

  ui:
    image: liquidinvestigations/hoover-ui
    volumes:
      - ./ui/build:/opt/hoover/ui/build

  search:
    image: liquidinvestigations/hoover-search
    volumes:
      - ./ui/build:/opt/hoover/ui/build
      - ./volumes/metrics:/opt/hoover/metrics
      - ./search-settings.py:/opt/hoover/search/hoover/site/settings/local.py
      - ./search-settings-testing.py:/opt/hoover/search/hoover/site/settings/testing_local.py
    depends_on:
      - search-pg
      - search-es
      - ui
      - snoop
    env_file:
      - search.env
    ports:
      - 45024:80

volumes:
  snoop-stats-es-data: {}
