version: "2"

volumes:
  snoop-stats-es-data: {}

services:
  snoop-rabbitmq:
    image: rabbitmq:3.7.3

  snoop-tika:
    image: logicalspark/docker-tikaserver

  snoop-stats-es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits: {memlock: {soft: -1, hard: -1}}
    volumes:
      - snoop-stats-es-data:/usr/share/elasticsearch/data

  snoop-stats-kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    depends_on:
      - snoop-stats-es
    environment:
      ELASTICSEARCH_URL: 'http://snoop-stats-es:9200'
    ports:
      - 45022:5601

  search-pg:
    image: postgres:9.6
    volumes:
      - ./volumes/search-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: search
      POSTGRES_DATABASE: search

  search-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    volumes:
      - ./volumes/search-es/data:/usr/share/elasticsearch/data
      - ./volumes/search-es-snapshots:/opt/hoover/es-snapshots
    environment:
      discovery.type: single-node
      path.repo: /opt/hoover/es-snapshots

  ui:
    image: liquidinvestigations/hoover-ui
    volumes:
      - ./ui/build:/opt/hoover/ui/build

  search:
    image: liquidinvestigations/hoover-search
    volumes:
      - ./ui/build:/opt/hoover/ui/build
      - ./volumes/metrics:/opt/hoover/metrics
      - ./settings/search-settings.py:/opt/hoover/search/hoover/site/settings/local.py
      - ./settings/search-settings-testing.py:/opt/hoover/search/hoover/site/settings/testing_local.py
    depends_on:
      - search-pg
      - search-es
      - ui
      - snoop--testdata
    env_file:
      - ./settings/search.env
    ports:
      - 45024:80
    environment:
      WAIT_HOSTS: search-es:9200, search-pg:5432
      WAIT_HOSTS_TIMEOUT: 60

  snoop-pg--testdata:
    image: postgres:9.6
    environment:
      POSTGRES_USER: snoop
      POSTGRES_DATABASE: snoop
    volumes:
      - ./volumes/snoop-pg--testdata/data:/var/lib/postgresql/data

  snoop-worker--testdata:
    image: liquidinvestigations/hoover-snoop2
    volumes:
      - ./gnupg:/opt/hoover/gnupg
      - ./collections:/opt/hoover/collections
      - ./settings/testdata/snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
      - ./snoop-blobs/testdata:/opt/hoover/snoop/blobs
    env_file:
      - ./settings/testdata/snoop.env
    depends_on:
      - snoop-rabbitmq
      - snoop-tika
      - snoop-stats-es
      - search-es
      - snoop-pg--testdata

  snoop--testdata:
    image: liquidinvestigations/hoover-snoop2
    volumes:
      - ./gnupg:/opt/hoover/gnupg
      - ./collections:/opt/hoover/collections
      - ./volumes/search-es-snapshots:/opt/hoover/es-snapshots
      - ./settings/testdata/snoop-settings.py:/opt/hoover/snoop/snoop/localsettings.py
      - ./snoop-blobs/testdata:/opt/hoover/snoop/blobs
    ports:
      - 45025:80
    env_file:
      - ./settings/testdata/snoop.env
    environment:
      WAIT_HOSTS: search-es:9200, snoop-pg--testdata:5432
      WAIT_HOSTS_TIMEOUT: 60
    depends_on:
      - snoop-rabbitmq
      - snoop-tika
      - snoop-stats-es
      - search-es
      - snoop-pg--testdata

